import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import '../styles/_typography.sass';
import { ThemeProvider } from 'next-themes';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable}`} suppressHydrationWarning>
      <body>
        <ThemeProvider enableSystem={false} defaultTheme="light">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
