import type { Metadata } from 'next';
import { Manrope, Inter } from 'next/font/google';
import './globals.css';
import '../styles/_typography.sass';
import { ThemeProvider } from 'next-themes';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(manrope.variable, 'font-sans', inter.variable)}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider enableSystem={false} defaultTheme="light">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
